name: "Katie Ball, designer"
description: "JEKYLL OVERDOSE"


baseurl: /jekyll-overdose
url: http://localhost:4000


paginate: 10


markdown: rdiscount
permalink: :year/:month/:title.html
pygments: true


include: ['_blog']
relative_permalinks: false
